import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider } from "@/components/ui/sidebar";
import { MinimalIntegrationSidebar } from "@/components/integration-sidebar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
			>
				<Providers>
					<SidebarProvider defaultOpen={true}>
						<div className="flex w-full h-screen">
							<MinimalIntegrationSidebar />
							<main
								className="flex-1
              w-full
               overflow-auto"
							>
								{children}
							</main>
						</div>
					</SidebarProvider>
					<Toaster />
				</Providers>
			</body>
		</html>
	);
}
